google_sheets:
  url: "https://docs.google.com/spreadsheets/d/1L-HKqOh58Z3PR89JQRJkqEN7XJ3f3nWW4TLTHHUpFCU/edit?gid=0"
  sheet_name: "Data"
  structure:
    column_a: "Отметка о публикации"
    column_b: "Заголовок"
    column_c: "Описание"
    column_d: "Тип"
    column_e: "Цена"
    column_f: "Дата"
    column_g: "Время"
    column_h: "Город"
    column_i: "Название заведения"
    column_j: "Адрес"
    column_k: "Источник"
    column_l: "Контакты"
    column_m: "Фото URL 1"
    column_n: "Видео URL 1"

target_site:
  url: "https://admin.egolist.ua/events/create"
  auth:
    username: "admin@admin.com"
    password: "12345678"
  form_mapping:
    name: "#name"
    descr: "#descr"
    type_event: "#type_event"
    price: "#price"
    date_event: "#date_event"
    time_event: "#time_event"
    town: "#town"
    name_estab: "#name_estab"
    addr_estab: "#addr_estab"
    link_estab: "#link_estab"
    contact_estab: "#contact_estab"
    photo_0: "#photo_0"
    video_0: "#video_0"
  submit_button: "span:contains('Создать')"
